rooms:
  - name: "한올 주주 회식방"
    admin: false
    package_name: "com.kakao.talk"
    persona_path: "config/personas/room1.md"
    features:
      youtube_summary: true
      llm_chat: true
      hanall_briefing: true
      weather: true
      child_age: false
      admin_commands: false
    hanall_publish_time: "08:30"
    weather:
      enabled: true
      location_label: "김해율하"
      grid_x: 95
      grid_y: 77
      publish_time: "08:13"

  - name: "한올테맨"
    admin: false
    package_name: "com.kakao.talk"
    persona_path: "config/personas/room1.md"
    features:
      youtube_summary: true
      llm_chat: false
      hanall_briefing: true
      weather: false
      child_age: false
      admin_commands: false
    hanall_publish_time: "08:25"
    weather:
      enabled: false
      location_label: "김해율하"
      grid_x: 95
      grid_y: 77
      publish_time: "08:10"

  - name: "테스트하는방방방"
    admin: false
    package_name: "com.kakao.talk"
    persona_path: "config/personas/room2.md"
    features:
      youtube_summary: true
      llm_chat: true
      hanall_briefing: true
      weather: true
      child_age: true
      admin_commands: false
    hanall_publish_time: "08:02"
    weather:
      enabled: true
      location_label: "서울강남"
      grid_x: 62
      grid_y: 125
      publish_time: "08:11"


  - name: "가족방"
    admin: false
    package_name: "com.kakao.talk"
    persona_path: "config/personas/room3.md"
    features:
      youtube_summary: true
      llm_chat: true
      hanall_briefing: false
      weather: true
      child_age: true
      admin_commands: false
    weather:
      enabled: true
      location_label: "김해율하"
      grid_x: 95
      grid_y: 77
      publish_time: "08:06"

  - name: "현기휘태"
    admin: false
    package_name: "com.kakao.talk"
    persona_path: "config/personas/room2.md"
    features:
      youtube_summary: true
      llm_chat: true
      hanall_briefing: false
      weather: true
      child_age: false
      admin_commands: false
    #hanall_publish_time: "09:00"
    weather:
      enabled: true
      location_label: "서울강남"
      grid_x: 62
      grid_y: 125
      publish_time: "08:05"

  - name: "초딩펨"
    admin: false
    package_name: "com.kakao.talk"
    persona_path: "config/personas/room2.md"
    features:
      youtube_summary: true
      llm_chat: true
      hanall_briefing: false
      weather: true
      child_age: false
      admin_commands: false
    #hanall_publish_time: "09:00"
    weather:
      enabled: true
      location_label: "김해율하"
      grid_x: 95
      grid_y: 77
      publish_time: "08:10"

  - name: "김휘태"
    admin: true
    package_name: "com.kakao.talk"
    features:
      youtube_summary: false
      llm_chat: false
      hanall_briefing: false
      weather: false
      child_age: false
      admin_commands: true
